plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

remote_theme: kosatyi/sjt

navigation: false
projects: false

url: https://kosatyi.com
baseurl: /ejs



brand: @kosatyi/ejs
title: Embedded JavaScript templates
description: EJS with extend/block support
analytics: UA-37629144-1
adsense: ca-pub-3650650669153101

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/


